USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON RMST_AGENT
REBUILD;
ALTER INDEX ALL ON RMSPROPERTY
REBUILD;
ALTER INDEX ALL ON RMSCOUNTRY
REBUILD;
ALTER INDEX ALL ON RMSCITY
REBUILD;
ALTER INDEX ALL ON RMSCONTACT
REBUILD;
ALTER INDEX ALL ON RMSPHOTOALBUM
REBUILD;
GO